server:
  port: 8081

eureka:
  instance:
    hostname: www.eureka1.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://www.eureka2.com:8080/eureka/