#server:
#  port: 9091
#
#spring:
#  application:
#    name: user-provider
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://www.eureka1.com:8080/eureka/,http://www.eureka2.com:8081/eureka/
#  instance:
#    instance-id: user2
#    prefer-ip-address: true