server:
  port: 6061
spring:
  application:
    name: consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka1.com:8080/eureka/,http://www.eureka2.com:8081/eureka/
    register-with-eureka: true